/** @file */
#include "main.h"




char msg[40];				/**< The output message of the board. */
uint8_t msgLen = 0;			/**< The current length of the output message. */
DHT_DATA dht;				/**< DHT11 sensor output data struct. */
fsm_type state = INIT_S;	/**< The current state of the FSM. */
int main(void){
	while (1){
		switch(state){
			case INIT_S: initState(); break;
			case IDLE_S: idleState(); break;
			case CAPTURE_S: captureState(); break;
			case SEND_S: sendState(); break;
			case ERROR_S: errState(); break;
		}
	}
}
/***********************************************//**
* Initialization state of the board. In this state,
* the board will initialize the DHT11 sensor, watchdog, 
* and USART6. Finally it
* will start the Watchdog countdown and put the 
* FSM in the idle state.
**************************************************/
void initState(){
	initWatchDog();
	DHT11_init();
	USART6_Init(9600);
	WD_ResetCounter();
	state = IDLE_S;
}

/***********************************************//**
* Idle state of the board. In this state, the board
* will first restart the watchdog counter and then
* wait 10 secs before restarting the watchdog and
* putting the FSM in capture state.
**************************************************/
void idleState(){
	int i;
	WD_ResetCounter();
	for(i = 0; i < 200; i++){ 
	delay(65000);
	}
	WD_ResetCounter();
	state = CAPTURE_S;
}


/***********************************************//**
* Capture state of the board. Will first read the DHT11
* sensor with the interrupts disabled for more accurate
* timing. After  that, it will re-enable interrupts and 
* will put the FSM in send state.
**************************************************/
void captureState(){
	disableIRQs();
	dht = DHT11_readSensor();
	enableIRQs();
	state = SEND_S;
}

/***********************************************//**
* Send state of the board. Will prepare the temp and
* humidity messages, and send them via usart. Will
* put the FSM in idle mode again.
**************************************************/
void sendState(){
	prepareMsg(msg, SEN_TEMP_ID, dht.temp);
	USART_transmitString(USART6, (uint8_t *)msg, msgLen);
	delay(1000);
	prepareMsg(msg, SEN_HUM_ID, dht.humd);
	USART_transmitString(USART6, (uint8_t *)msg, msgLen);
	delay(1000);
	state = IDLE_S;
}

/***********************************************//**
* Error state of the board.
**************************************************/
void errState(){
	
}

/***********************************************//**
* Starts the watchdog with the desired settings.
**************************************************/
void initWatchDog(){
	WD_SetPreescaler(7);
	WD_SetDebugMode(1);
	WD_Start();
}
/***********************************************//**
* Enables the IRQs of the USART6.
**************************************************/
void enableIRQs(){
	NVIC_EnableIRQ(USART6_IRQn);
}

/***********************************************//**
* Disables the IRQs of the USART6.
**************************************************/
void disableIRQs(){
	NVIC_DisableIRQ(USART6_IRQn);
}

/***********************************************//**
* Prepares the message with the correct format to be sent.
* @param msg The pointer where the message will be stored.
* @param sensor The sensor ID.
* @param value The value generated by that sensor.
**************************************************/
void prepareMsg(char *msg, uint8_t sensor, float value){
	msgLen = sprintf(msg, "$%i%%%i%%%f$\n", BOARD_ID, sensor, value);
}